"""Regenerate core/default_configs.py from the files in configs/.

Run this after every change in configs/ so the exe ships the same defaults:
    python embed_default_configs.py
"""
from __future__ import annotations

from pathlib import Path

PROJECT_DIR = Path(__file__).parent
CONFIGS_DIR = PROJECT_DIR / "configs"
TARGET = PROJECT_DIR / "core" / "default_configs.py"

MODULE_TEMPLATE = '''# Generated by embed_default_configs.py from configs/. Do not edit by hand.
from __future__ import annotations

import json
from pathlib import Path

DEFAULT_FILES: dict[str, str] = {{
{entries}
}}


def restore_default_configs(base_dir: str) -> None:
    for rel_path, content in DEFAULT_FILES.items():
        target = Path(base_dir) / rel_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content + "\\n", encoding="utf-8")


def upgrade_outdated_configs(base_dir: str) -> list[str]:
    """Replace config files whose config_version is older than the bundled default.

    User-editable configs keep their version, so only program-owned files whose
    default changed are replaced. The old file is kept next to it as .bak.
    """
    messages: list[str] = []
    for rel_path, content in DEFAULT_FILES.items():
        target = Path(base_dir) / rel_path
        if not target.exists():
            continue

        try:
            current_version = json.loads(target.read_text(encoding="utf-8")).get("config_version")
        except (json.JSONDecodeError, OSError, AttributeError):
            continue  # left to config validation and the restore prompt

        bundled_version = json.loads(content)["config_version"]
        if not isinstance(current_version, int) or current_version >= bundled_version:
            continue

        backup = target.with_name(f"{{target.name}}.v{{current_version}}.bak")
        target.replace(backup)
        target.write_text(content + "\\n", encoding="utf-8")
        messages.append(
            f"Config {{rel_path}} upgraded from v{{current_version}} to v{{bundled_version}}; "
            f"old file kept as {{backup.name}}"
        )
    return messages
'''


def main() -> None:
    entries = []
    for path in sorted(CONFIGS_DIR.rglob("*.json")):
        rel_path = path.relative_to(PROJECT_DIR).as_posix()
        content = path.read_text(encoding="utf-8").rstrip("\n")
        entries.append(f"    {rel_path!r}: {content!r},")

    TARGET.write_text(MODULE_TEMPLATE.format(entries="\n".join(entries)), encoding="utf-8")
    print(f"Embedded {len(entries)} config files into {TARGET.relative_to(PROJECT_DIR)}")


if __name__ == "__main__":
    main()
